version: "3.8"

services:
  flight_search:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
#    command: bash -c "cd flight_search && pytest . "
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flight_search
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 2
