# Generated by Django 4.2.19 on 2025-04-10 04:29

from django.db import migrations


def create_initial_flight_companies(apps, schema_editor):
    FlightCompany = apps.get_model('auth_manager', 'FlightCompany')
    FlightCompany.objects.create(name="Indigo")
    FlightCompany.objects.create(name="Air India")
    FlightCompany.objects.create(name="SpiceJet")


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager', '0001_initial')
    ]

    operations = [
        migrations.RunPython(create_initial_flight_companies),
    ]
